name: Build

on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    name: ci/github/scan-vulnerabilities
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x
    - name: Scan for Vulnerabilities
      shell: bash
      run: |
        cd src
        dotnet restore
        dotnet list package --vulnerable --include-transitive | tee vulnerabilities.txt
        ! cat vulnerabilities.txt | grep -q "has the following vulnerable packages"
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        framework: [net8.0]
        test: [".Tests"]
        configuration: [release]
        docker-tag: ['ci']
    runs-on: ${{ matrix.os }}
    name: ci/github/build-${{ matrix.os }}/${{ matrix.framework }}/EventStore.Plugins${{ matrix.test }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          8.0.x
    - name: Compile
      shell: bash
      run: |
        dotnet build --configuration ${{ matrix.configuration }} --framework=${{ matrix.framework }} src/EventStore.Plugins${{ matrix.test }}
    - name: Run Tests
      shell: bash
      run: |
        dotnet test --configuration ${{ matrix.configuration }} --framework=${{ matrix.framework }} --blame \
        --logger:"GitHubActions;report-warnings=false" \
        --logger:"console;verbosity=normal" \
        test/EventStore.Plugins${{ matrix.test }}
