name: Build

on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*

env:
  DOTNET_SDK_VERSION: 3.1.201
jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    name: ci/github/scan-vulnerabilities
    container: mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Scan for Vulnerabilities
      run: |
        cd src
        dotnet tool restore
        dotnet restore
        dotnet tool run dotnet-retire
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]
        test: [".Tests"]
        configuration: [release]
        docker-tag: ['ci']
    runs-on: ${{ matrix.os }}
    name: ci/github/build-${{ matrix.os }}/EventStore.Plugins${{ matrix.test }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Dotnet
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
    - name: Compile
      shell: bash
      run: |
        dotnet build --configuration ${{ matrix.configuration }} src/EventStore.Plugins${{ matrix.test }}
    - name: Run Tests
      shell: bash
      run: |
        dotnet test --configuration ${{ matrix.configuration }} --blame \
        --logger:html --logger:trx --logger:"console;verbosity=normal" \
        --results-directory=$(pwd)/test-results/EventStore.Plugins${{ matrix.test }} \
        src/EventStore.Plugins${{ matrix.test }}
    - name: Collect Test Results
      shell: bash
      if: always()
      run: |
        echo $(find ./test-results -name "*.html" | xargs cat) > test-results.html
    - name: Publish Test Results (HTML)
      uses: actions/upload-artifact@v1
      if: always()
      with:
        path: test-results.html
        name: test-results-${{ matrix.configuration }}-EventStore.Plugins${{ matrix.test }}.html
    - name: Publish Test Results (All)
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: test-results-${{ matrix.configuration }}-EventStore.Plugins${{ matrix.test }}
        path: test-results
